name: Create Release Draft

on:
  workflow_dispatch:
    inputs:
      releaseName:
        description: 'Name for this release (should be equivalent to the tag without the v prefix)'
        required: true
        default: 'X.Y.Z'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
    name: Create Release
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npx @kinvolk/headlamp-plugin lint .
      - run: npx @kinvolk/headlamp-plugin tsc .
      - run: npx @kinvolk/headlamp-plugin build .

      - name: create-archive
        run: tar -czf ${{ github.event.repository.name }}-${{ github.event.inputs.releaseName }}.tar.gz dist/main.js package.json
      - name: create-checksum
        id: create-checksum
        run: sha256sum ${{ github.event.repository.name }}-${{ github.event.inputs.releaseName }}.tar.gz > checksum.txt
      - name: create-release
        uses: pyTooling/Actions/releaser@r0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          rm: true
          tag: ${{ github.event.inputs.releaseName }}
          files: |
            ${{ github.event.repository.name }}-${{ github.event.inputs.releaseName }}.tar.gz
            checksum.txt

