name: Create Release Draft

on:
  push:
    tags:
      - "v*.*.*"
      
permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
    name: Create Release
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npx @kinvolk/headlamp-plugin lint .
      - run: npx @kinvolk/headlamp-plugin tsc .
      - run: npx @kinvolk/headlamp-plugin build .

      - name: create-archive
        run: |
          mkdir -p kubescape-plugin
          cp dist/main.js package.json kubescape-plugin
          tar -czf ${{ github.event.repository.name }}-${{ github.event.inputs.releaseName }}.tar.gz kubescape-plugin
      - name: create-checksum
        id: create-checksum
        run: sha256sum ${{ github.event.repository.name }}-${{ github.event.inputs.releaseName }}.tar.gz > checksum.txt
      - name: Create Release Draft
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ github.token }}
          draft: true
          name: ${{ github.event.inputs.releaseName }}
          files: |
            ${{ github.event.repository.name }}-${{ github.event.inputs.releaseName }}.tar.gz
            checksum.txt

